### PR TITLE
#119: Use the Drupal.org API to bypass user page access restrictions.

### LINKED ISSUE #119: Companies and countries are now broken as d.o returns '403 Unauthorized'
Drupal.org has some kind of spambot prevention in place that easily kicks in when running the drupalcores company + country mapping.

The open(url) call to the user page throws an exception with message '403 Unauthorized'.

To solve this, we either have to login and issue these calls with a cookie, or somehow get the company + country mappings from a different data source.

### PR DESCRIPTION
**Pull request by jcnventura**
This fixes #119.

It's a major rewrite of the companies.rb and countries.rb.

The json.rb no longer lowercases the contributor names (nor replace - with _), but the name mapping still uses lowercased keys. Because d.o user URLs are not case-sensitive, I've kept those lowercase. I've also adapted the commit message parser to accept '-' in usernames and to reduce some false positives when using 'by' somewhere in commit description followed by a class::method.

Finally, I added a mapping between 2-letter country codes and English names, using as source the d.o user edit form. This is needed because the user.json response only specifies the 2-letter code. Norway had some problems as for some reason the hash key gets saved as >'no'< and not simply >no<.

### CODE REVIEW

File: app/bin/countries.rb [hunk 1]
```diff
@@ -3,20 +3,23 @@
...
+COMPANY_NOT_SPECIFIED='Not specified'
 UPDATE_NONE=0
 UPDATE_NOT_FOUND=1
 UPDATE_ALL=2
 
+country_names = YAML::load_file('../config/country_names.yml')
 name_variants = Hash.new(0)
-if File.exists? ('../data/company_infos.yml')
-  companies_info = YAML::load_file('../data/company_infos.yml')
+Dir.mkdir('../data') unless Dir.exist?('../data')
```
Comment (borisson) [inline app/bin/countries.rb]: We should probably also add this mkdir to the `companies.rb`?

File: app/bin/countries.rb [hunk 2]
```diff
@@ -44,90 +47,62 @@
 contributors = data['contributors']
 companies = Hash.new(0)
 
-def ensure_company(companies, companies_info, key, title, link)
+def ensure_company(companies, companies_info, key, title)
```
Comment (borisson) [inline app/bin/countries.rb]: While we're changing this can we rename it to `ensure_country`? Or is that too much of a refactor?

**Comment by lauriii** [comment]
Tested this locally and the companies generation works again. Thank you @jcnventura for working on this! 🙏
